name: recam
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.5.25=h06a4308_1
  - certifi=2021.5.30=py36h06a4308_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - dataclasses=0.8=pyh4f3eec9_6
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h5ab3b9f_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.2.0=h06a4308_610
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.1=h27cfd23_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1k=h27cfd23_0
  - pillow=8.2.0=py36he98fc37_0
  - pip=21.1.2=py36h06a4308_0
  - python=3.6.13=h12debd9_1
  - pytorch=1.9.0=py3.6_cuda11.1_cudnn8.0.5_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py36h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.9.0=py36
  - torchvision=0.10.0=py36_cu111
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - unzip=6.0=h611a1e1_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.13.0
    - addict==2.4.0
    - albumentations==1.1.0
    - antlr4-python3-runtime==4.8
    - blessings==1.7
    - cachetools==4.2.2
    - chainer==7.8.0
    - chainercv==0.13.1
    - chardet==4.0.0
    - click==8.0.1
    - cycler==0.10.0
    - cython==0.29.23
    - decorator==4.4.2
    - filelock==3.0.12
    - google-auth==1.31.0
    - google-auth-oauthlib==0.4.4
    - gpustat==0.6.0
    - grpcio==1.38.0
    - idna==2.10
    - imageio==2.9.0
    - importlib-metadata==4.5.0
    - joblib==1.0.1
    - jsonpatch==1.32
    - jsonpointer==2.1
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.3.4
    - munch==2.5.0
    - mxnet==1.8.0.post0
    - networkx==2.5.1
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.1
    - omegaconf==2.1.0
    - opencv-python==4.5.2.54
    - opencv-python-headless==4.5.4.58
    - pandas==1.1.5
    - protobuf==3.17.3
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.2
    - pydensecrf==1.0rc2
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.3
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - pyzmq==22.1.0
    - qudida==0.0.4
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-image==0.17.2
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.4
    - threadpoolctl==3.0.0
    - tifffile==2020.9.3
    - torchfile==0.1.0
    - torchnet==0.0.4
    - tornado==6.1
    - tqdm==4.61.1
    - urllib3==1.26.5
    - visdom==0.1.8.9
    - websocket-client==1.1.0
    - werkzeug==2.0.1
    - zipp==3.4.1
